---
# Source: tailscale-operator/templates/oauth-secret.yaml
# Copyright (c) Tailscale Inc & AUTHORS
# SPDX-License-Identifier: BSD-3-Clause

apiVersion: v1
kind: Secret
metadata:
  name: operator-oauth
  namespace: tailscale
stringData:
  client_id: kxAPei1jGn11CNTRL
  client_secret: tskey-client-kxAPei1jGn11CNTRL-16L1XsGucsTPmsH9njzomTG6BcfUPksvY
