---
# Source: external-dns/templates/clusterrolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: external-dns-default
  namespace: "default"
  labels: 
    app.kubernetes.io/name: external-dns
    helm.sh/chart: external-dns-6.12.2
    app.kubernetes.io/instance: external-dns
    app.kubernetes.io/managed-by: Helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: external-dns-default
subjects:
  - kind: ServiceAccount
    name: external-dns
    namespace: "default"
