---
# Source: external-dns/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: external-dns
  namespace: "default"
  labels: 
    app.kubernetes.io/name: external-dns
    helm.sh/chart: external-dns-6.12.2
    app.kubernetes.io/instance: external-dns
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  sessionAffinity: None
  ports:
    - name: http
      port: 7979
      protocol: TCP
      targetPort: http
  selector: 
    app.kubernetes.io/name: external-dns
    app.kubernetes.io/instance: external-dns
