---
# Source: external-dns/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-dns
  namespace: "default"
  labels: 
    app.kubernetes.io/name: external-dns
    helm.sh/chart: external-dns-6.12.2
    app.kubernetes.io/instance: external-dns
    app.kubernetes.io/managed-by: Helm
  annotations:
automountServiceAccountToken: true
