---
namePrefix: dev-
resources:
- ../base
- svc-db.yaml

helmCharts:
- name: postgresql
  version: "11.1.28"
  repo: https://charts.bitnami.com/bitnami
  releaseName: postgresql
  valuesInline:
    metrics:
      enabled: true
    auth:
      postgresPassword: testme
      database: default

configMapGenerator:
- name: prometheus-server
  behavior: merge
  files:
  - prometheus.yml=prometheus.yaml
- name: grafana
  behavior: merge
  files:
  - grafana.ini
  - datasources.yaml=grafana-datasources.yaml
- name: invidious-config
  files:
  - config.yml=invidious-config.yaml
- name: element-config
  files:
  - config.json=element-config.json

secretGenerator:
- name: grafana-credentials
  literals:
  - admin-user=rob
  - admin-password=testme
- name: invidious-credentials
  literals:
  - database-url=postgresql://kemal:testme@dev-db:5432/invidious
  # Individual keys required by init-invidious-db:
  - database-host=dev-db
  - database-port=5432
  - database-name=invidious
  - database-user=kemal
  - database-password=testme

patches:
# Patch the metrics-server to not require TLS in dev cluster.
- target:
    kind: Deployment
    name: metrics-server
  path: deploy-metrics-server.yaml
# Patch the ingress-nginx deployment to allow it to use a service with a
# namePrefix. See https://github.com/kubernetes/ingress-nginx/issues/2599#issuecomment-601170289.
- target:
    kind: Deployment
    name: ingress-nginx-controller
  path: deploy-ingress-nginx.yaml

# Patch the ingress-nginx-admission-create job to reference its webhook with a
# namePrefix.
- target:
    kind: Job
    name: ingress-nginx-admission-create
  path: job-ingress-nginx-admission-create.yaml

# Patch the ingress-nginx-admission-patch job to reference its webhook with a
# namePrefix.
- target:
    kind: Job
    name: ingress-nginx-admission-patch
  path: job-ingress-nginx-admission-patch.yaml

# Patch the ingress resource with stage-specific hostnames:
- target:
    kind: Ingress
    name: ingress
  path: ingress.yaml

# Patch Grafana deployment to inject PostgreSQL credentials:
- target:
    kind: Deployment
    name: grafana
  path: deploy-grafana.yaml
