---
namePrefix: dev-
resources:
- ../base
- svc-db.yaml

helmCharts:
- name: postgresql
  version: "11.1.28"
  repo: https://charts.bitnami.com/bitnami
  releaseName: postgresql
  valuesInline:
    metrics:
      enabled: true
    auth:
      postgresPassword: testme
      database: default

configMapGenerator:
- name: prometheus-server
  behavior: merge
  files:
  - prometheus.yml=prometheus.yaml

patches:
# Patch the ingress-nginx deployment to allow it to use a service with a
# namePrefix. See https://github.com/kubernetes/ingress-nginx/issues/2599#issuecomment-601170289.
- target:
    kind: Deployment
    name: ingress-nginx-controller
  path: deploy-ingress-nginx.yaml
