---
apiVersion: v1
kind: Service
metadata:
  name: "db"
spec:
  type: ExternalName
  externalName: "dev-postgresql.default.svc.cluster.local"
---
apiVersion: v1
kind: Service
metadata:
  name: "db-metrics"
spec:
  type: ExternalName
  externalName: "dev-postgresql-metrics.default.svc.cluster.local"
