---
# Source: prometheus/templates/node-exporter/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    component: "node-exporter"
    app: prometheus
    release: prometheus
    chart: prometheus-15.8.6
    heritage: Helm
  name: prometheus-node-exporter
  namespace: default
  annotations:
    {}
