global: {}
receivers:
- name: mailgun-receiver
  email_configs:
  - to: alerts@netflux.io
    from: alerts@netflux.io
    smarthost: smtp.eu.mailgun.org:587
    auth_username: test@example.com
    auth_password: foobar
    send_resolved: true
route:
  group_interval: 5m
  group_wait: 10s
  receiver: mailgun-receiver
  repeat_interval: 3h
templates:
- /etc/alertmanager/*.tmpl
