---
# Source: kubernetes-replicator/templates/rbac.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubernetes-replicator
  labels:
    helm.sh/chart: kubernetes-replicator-2.7.3
    app.kubernetes.io/name: kubernetes-replicator
    app.kubernetes.io/instance: kubernetes-replicator
    app.kubernetes.io/version: "v2.7.3"
    app.kubernetes.io/managed-by: Helm
---
# Source: kubernetes-replicator/templates/rbac.yaml
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kubernetes-replicator
  labels:
    helm.sh/chart: kubernetes-replicator-2.7.3
    app.kubernetes.io/name: kubernetes-replicator
    app.kubernetes.io/instance: kubernetes-replicator
    app.kubernetes.io/version: "v2.7.3"
    app.kubernetes.io/managed-by: Helm
rules:
  - apiGroups: [ "" ]
    resources: [ "namespaces" ]
    verbs: [ "get", "watch", "list" ]
  - apiGroups: [""]
    resources: ["secrets", "configmaps"]
    verbs: ["get", "watch", "list", "create", "update", "patch", "delete"]
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["roles", "rolebindings"]
    verbs: ["get", "watch", "list", "create", "update", "patch", "delete"]
---
# Source: kubernetes-replicator/templates/rbac.yaml
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kubernetes-replicator
  labels:
    helm.sh/chart: kubernetes-replicator-2.7.3
    app.kubernetes.io/name: kubernetes-replicator
    app.kubernetes.io/instance: kubernetes-replicator
    app.kubernetes.io/version: "v2.7.3"
    app.kubernetes.io/managed-by: Helm
roleRef:
  kind: ClusterRole
  name: kubernetes-replicator
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: kubernetes-replicator
    namespace: "default"
