- op: replace
  path: /spec/ingressClassName
  value: prod-nginx
- op: add
  # https://github.com/kubernetes-sigs/kustomize/issues/1439#issuecomment-520614831
  path: /metadata/annotations/cert-manager.io~1cluster-issuer
  value: letsencrypt-production
- op: replace
  path: /spec/tls
  value:
    - hosts:
      - grafana.netflux.io
      - tube.netflux.io
      - element.netflux.io
      - git.netflux.io
      - drone.netflux.io
      secretName: prod-ingress-tls
- op: replace
  path: /spec/rules/0/host
  value: grafana.netflux.io
- op: replace
  path: /spec/rules/1/host
  value: tube.netflux.io
- op: replace
  path: /spec/rules/2/host
  value: element.netflux.io
- op: replace
  path: /spec/rules/3/host
  value: git.netflux.io
- op: replace
  path: /spec/rules/4/host
  value: drone.netflux.io
