- op: replace
  path: /spec/ingressClassName
  value: prod-nginx
- op: add
  # https://github.com/kubernetes-sigs/kustomize/issues/1439#issuecomment-520614831
  path: /metadata/annotations/cert-manager.io~1cluster-issuer
  value: prod-letsencrypt
- op: replace
  path: /spec/tls
  value:
    - hosts:
      - grafana.netflux.io
      - tube.netflux.io
      - element.netflux.io
      - drone.netflux.io
      - synapse.netflux.io
      - netflux.io
      - caldav.netflux.io
      - solar-gateway.netflux.io
      secretName: prod-ingress-tls
- op: replace
  path: /spec/rules/0/host
  value: grafana.netflux.io
- op: replace
  path: /spec/rules/1/host
  value: tube.netflux.io
- op: replace
  path: /spec/rules/2/host
  value: element.netflux.io
- op: replace
  path: /spec/rules/4/host
  value: drone.netflux.io
- op: replace
  path: /spec/rules/5/host
  value: synapse.netflux.io
- op: replace
  path: /spec/rules/6/host
  value: netflux.io
- op: replace
  path: /spec/rules/7/host
  value: caldav.netflux.io
- op: replace
  path: /spec/rules/8/host
  value: solar-gateway.netflux.io
