namePrefix: prod-
resources:
- ../base
- svc-db.yaml
- svc-netflux.yaml

configMapGenerator:
- name: prometheus-server
  behavior: merge
  files:
  - prometheus.yml=prometheus.yaml

secretGenerator:
- name: prometheus-credentials
  files:
  - secrets/exporter-password

patches:
# Patch prometheus-server pod to mount the secrets volume.
- target:
    kind: Deployment
    name: prometheus-server
  patch: |-
    - op: add
      path: /spec/template/spec/volumes/-
      value:
        secret:
          defaultMode: 420
          secretName: prod-prometheus-credentials
        name: secrets-volume
    - op: add
      path: /spec/template/spec/containers/1/volumeMounts/-
      value:
        mountPath: /etc/secrets
        name: secrets-volume
        readOnly: true

# Patch the ingress-nginx deployment to allow it to use a service with a
# namePrefix. See https://github.com/kubernetes/ingress-nginx/issues/2599#issuecomment-601170289.
- target:
    kind: Deployment
    name: ingress-nginx-controller
  path: deploy-ingress-nginx.yaml
