---
apiVersion: v1
kind: Service
metadata:
  name: db
  annotations:
    ignore-check.kube-linter.io/dangling-service: "This is a headless service"
spec:
  clusterIP: None
  ports:
  - name: postgres
    port: 5432
    protocol: TCP
---
kind: Endpoints
apiVersion: v1
metadata:
  name: db
subsets:
  - addresses:
      - ip: ${POSTGRESQL_IP}
    ports:
      - port: 5432
        name: postgres
        protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: db-metrics
  annotations:
    ignore-check.kube-linter.io/dangling-service: "This is a headless service"
spec:
  clusterIP: None
  ports:
  - name: postgres-exporter
    port: 9187
    protocol: TCP
---
kind: Endpoints
apiVersion: v1
metadata:
  name: db-metrics
subsets:
  - addresses:
      - ip: ${POSTGRESQL_IP}
    ports:
      - port: 9187
        name: postgres-exporter
        protocol: TCP
