---
apiVersion: v1
kind: Service
metadata:
  name: netflux
  annotations:
    ignore-check.kube-linter.io/dangling-service: "This is a headless service"
spec:
  clusterIP: None
  ports:
  - name: metrics
    port: 9100
    protocol: TCP
---
kind: Endpoints
apiVersion: v1
metadata:
  name: netflux
subsets:
  - addresses:
      - ip: ${NETFLUX_PRIVATE_IP}
    ports:
      - port: 9100
        name: metrics
        protocol: TCP
