apiVersion: apps/v1
kind: Deployment
metadata:
  name: element
  labels:
    app.kubernetes.io/name: element
    app.kubernetes.io/instance: element
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: element
      app.kubernetes.io/instance: element
  template:
    metadata:
      labels:
        app.kubernetes.io/name: element
        app.kubernetes.io/instance: element
    spec:
      containers:
        - name: element
          image: vectorim/element-web:latest
          volumeMounts:
            - name: config
              mountPath: /app/config.json
              subPath: config.json
          ports:
          - containerPort: 80
            name: http
            protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            requests:
              memory: "32Mi"
              cpu: "50m"
            limits:
              memory: "64Mi"
              cpu: "500m"
      volumes:
        - name: config
          configMap:
            name: element-config
