---
helmCharts:
- name: ingress-nginx
  version: "4.1.0"
  repo: https://kubernetes.github.io/ingress-nginx
  includeCRDs: true
  releaseName: ingress-nginx
  valuesInline:
    controller:
      publishService:
        enabled: true
      metrics:
        enabled: true
        service:
          annotations:
            prometheus.io/scrape: "true"
            prometheus.io/port: "10254"
