---
resources:
# ingress-nginx
- inflated/ingress-nginx/templates/controller-deployment.yaml
- inflated/ingress-nginx/templates/controller-serviceaccount.yaml
- inflated/ingress-nginx/templates/controller-rolebinding.yaml
- inflated/ingress-nginx/templates/controller-ingressclass.yaml
- inflated/ingress-nginx/templates/controller-service-metrics.yaml
- inflated/ingress-nginx/templates/clusterrole.yaml
- inflated/ingress-nginx/templates/controller-service.yaml
- inflated/ingress-nginx/templates/controller-service-webhook.yaml
- inflated/ingress-nginx/templates/controller-role.yaml
- inflated/ingress-nginx/templates/controller-configmap.yaml
- inflated/ingress-nginx/templates/admission-webhooks/job-patch/serviceaccount.yaml
- inflated/ingress-nginx/templates/admission-webhooks/job-patch/job-createSecret.yaml
- inflated/ingress-nginx/templates/admission-webhooks/job-patch/job-patchWebhook.yaml
- inflated/ingress-nginx/templates/admission-webhooks/job-patch/rolebinding.yaml
- inflated/ingress-nginx/templates/admission-webhooks/job-patch/role.yaml
- inflated/ingress-nginx/templates/admission-webhooks/job-patch/clusterrole.yaml
- inflated/ingress-nginx/templates/admission-webhooks/job-patch/clusterrolebinding.yaml
- inflated/ingress-nginx/templates/admission-webhooks/validating-webhook.yaml
- inflated/ingress-nginx/templates/clusterrolebinding.yaml
# Prometheus
- inflated/prometheus/charts/kube-state-metrics/templates/serviceaccount.yaml
- inflated/prometheus/charts/kube-state-metrics/templates/deployment.yaml
- inflated/prometheus/charts/kube-state-metrics/templates/role.yaml
- inflated/prometheus/charts/kube-state-metrics/templates/service.yaml
- inflated/prometheus/charts/kube-state-metrics/templates/clusterrolebinding.yaml
- inflated/prometheus/templates/node-exporter/daemonset.yaml
- inflated/prometheus/templates/node-exporter/serviceaccount.yaml
- inflated/prometheus/templates/node-exporter/svc.yaml
- inflated/prometheus/templates/pushgateway/serviceaccount.yaml
- inflated/prometheus/templates/pushgateway/service.yaml
- inflated/prometheus/templates/pushgateway/clusterrole.yaml
- inflated/prometheus/templates/pushgateway/deploy.yaml
- inflated/prometheus/templates/pushgateway/clusterrolebinding.yaml
- inflated/prometheus/templates/alertmanager/serviceaccount.yaml
- inflated/prometheus/templates/alertmanager/service.yaml
- inflated/prometheus/templates/alertmanager/clusterrole.yaml
- inflated/prometheus/templates/alertmanager/cm.yaml
- inflated/prometheus/templates/alertmanager/deploy.yaml
- inflated/prometheus/templates/alertmanager/clusterrolebinding.yaml
- inflated/prometheus/templates/alertmanager/pvc.yaml
- inflated/prometheus/templates/server/serviceaccount.yaml
- inflated/prometheus/templates/server/service.yaml
- inflated/prometheus/templates/server/clusterrole.yaml
- inflated/prometheus/templates/server/cm.yaml
- inflated/prometheus/templates/server/deploy.yaml
- inflated/prometheus/templates/server/clusterrolebinding.yaml
- inflated/prometheus/templates/server/pvc.yaml
# Grafana
- inflated/grafana/templates/serviceaccount.yaml
- inflated/grafana/templates/dashboards-json-configmap.yaml
- inflated/grafana/templates/rolebinding.yaml
- inflated/grafana/templates/deployment.yaml
- inflated/grafana/templates/role.yaml
- inflated/grafana/templates/service.yaml
- inflated/grafana/templates/clusterrole.yaml
- inflated/grafana/templates/podsecuritypolicy.yaml
- inflated/grafana/templates/configmap.yaml
- inflated/grafana/templates/clusterrolebinding.yaml

- ingress.yaml

- deploy-invidious.yaml
- svc-invidious.yaml
