---
resources:
- ../minimal-base
# ingress-nginx
- inflated/ingress-nginx/templates/controller-deployment.yaml
- inflated/ingress-nginx/templates/controller-serviceaccount.yaml
- inflated/ingress-nginx/templates/controller-rolebinding.yaml
- inflated/ingress-nginx/templates/controller-ingressclass.yaml
- inflated/ingress-nginx/templates/controller-service-metrics.yaml
- inflated/ingress-nginx/templates/clusterrole.yaml
- inflated/ingress-nginx/templates/controller-service.yaml
- inflated/ingress-nginx/templates/controller-service-webhook.yaml
- inflated/ingress-nginx/templates/controller-role.yaml
- inflated/ingress-nginx/templates/controller-configmap.yaml
- inflated/ingress-nginx/templates/admission-webhooks/job-patch/serviceaccount.yaml
- inflated/ingress-nginx/templates/admission-webhooks/job-patch/job-createSecret.yaml
- inflated/ingress-nginx/templates/admission-webhooks/job-patch/job-patchWebhook.yaml
- inflated/ingress-nginx/templates/admission-webhooks/job-patch/rolebinding.yaml
- inflated/ingress-nginx/templates/admission-webhooks/job-patch/role.yaml
- inflated/ingress-nginx/templates/admission-webhooks/job-patch/clusterrole.yaml
- inflated/ingress-nginx/templates/admission-webhooks/job-patch/clusterrolebinding.yaml
- inflated/ingress-nginx/templates/admission-webhooks/validating-webhook.yaml
- inflated/ingress-nginx/templates/clusterrolebinding.yaml
# Prometheus
- inflated/prometheus/charts/prometheus-node-exporter/templates/daemonset.yaml
- inflated/prometheus/charts/prometheus-node-exporter/templates/serviceaccount.yaml
- inflated/prometheus/charts/prometheus-node-exporter/templates/service.yaml
- inflated/prometheus/charts/alertmanager/templates/serviceaccount.yaml
- inflated/prometheus/charts/alertmanager/templates/services.yaml
- inflated/prometheus/charts/alertmanager/templates/configmap.yaml
- inflated/prometheus/charts/alertmanager/templates/statefulset.yaml
- inflated/prometheus/charts/kube-state-metrics/templates/serviceaccount.yaml
- inflated/prometheus/charts/kube-state-metrics/templates/deployment.yaml
- inflated/prometheus/charts/kube-state-metrics/templates/role.yaml
- inflated/prometheus/charts/kube-state-metrics/templates/service.yaml
- inflated/prometheus/charts/kube-state-metrics/templates/clusterrolebinding.yaml
- inflated/prometheus/charts/prometheus-pushgateway/templates/serviceaccount.yaml
- inflated/prometheus/charts/prometheus-pushgateway/templates/deployment.yaml
- inflated/prometheus/charts/prometheus-pushgateway/templates/service.yaml
- inflated/prometheus/templates/serviceaccount.yaml
- inflated/prometheus/templates/service.yaml
- inflated/prometheus/templates/clusterrole.yaml
- inflated/prometheus/templates/cm.yaml
- inflated/prometheus/templates/deploy.yaml
- inflated/prometheus/templates/clusterrolebinding.yaml
- inflated/prometheus/templates/pvc.yaml
# kubernetes-replicator
- inflated/kubernetes-replicator/templates/deployment.yaml
- inflated/kubernetes-replicator/templates/rbac.yaml
# external-dns
- inflated/external-dns/templates/serviceaccount.yaml
- inflated/external-dns/templates/deployment.yaml
- inflated/external-dns/templates/service.yaml
- inflated/external-dns/templates/clusterrole.yaml
- inflated/external-dns/templates/clusterrolebinding.yaml

- ingress.yaml

- deploy-invidious.yaml
- svc-invidious.yaml

- deploy-element.yaml
- svc-element.yaml

- deploy-drone.yaml
- svc-drone.yaml
- deploy-drone-runner.yaml
- role-drone-runner.yaml
- rolebinding-drone-runner.yaml

- statefulset-synapse.yaml
- svc-synapse.yaml

- statefulset-radicale.yaml
- svc-radicale.yaml

- deploy-solar-toolkit-gateway.yaml
- svc-solar-toolkit-gateway.yaml

configMapGenerator:
- name: invidious-scripts
  files:
  - init.sh=resources/invidious-init.sh
  options:
    labels:
      app: invidious

secretGenerator:
- name: aws-do-external-dns-credentials
  files:
  - credentials=secrets/aws-do-external-dns-credentials

patches:
# Patch the ingress-nginx service to expose port 22 for Gitea SSH access.
- target:
    kind: Service
    name: ingress-nginx-controller
  path: svc-ingress-nginx.yaml

- target:
    kind: Deployment
    name: ingress-nginx-controller
  path: deploy-ingress-nginx.yaml

- target:
    kind: ConfigMap
    name: ingress-nginx-controller
  path: config-map-ingress-nginx.yaml

- target:
    kind: Deployment
    name: external-dns
  path: deploy-external-dns.yaml
