---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: synapse-data
  namespace: default
  labels:
    app: synapse
    component: storage
    app.kubernetes.io/name: synapse
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
