---
# Add nodeports to the LoadBalancer service, this makes DigitalOcean create a
# corresponding forwarding rule.
#
# Setting the nodePort seems to be necessary for DO to create the forwarding
# rules.
- op: add
  path: /spec/ports/-
  value:
    nodePort: 32050
    port: 22
    name: ssh
