---
# Configure the ingress-nginx to use specific nodePorts for HTTP and HTTPS
# traffic. This allows the cluster to route traffic to the service via port
# mappings.
#
# TODO: use a NodePort service instead and remove the patches.
- op: replace
  path: /spec/ports/0/nodePort
  value: 32048
- op: replace
  path: /spec/ports/1/nodePort
  value: 32049
# Force the ingress-nginx service to expose port 22. This allows traffic to be
# routed to the Gitea SSH service.
- op: add
  path: /spec/ports/-
  value:
    nodePort: 32050
    port: 22
    name: ssh
