apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ingress-tls
  namespace: default
spec:
  secretName: prod-ingress-tls
  issuerRef:
    name: prod-letsencrypt
    kind: ClusterIssuer
  commonName: k3s.netflux.io
  dnsNames:
    - k3s.netflux.io
