apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ingress-tls
  namespace: default
spec:
  secretName: prod-ingress-tls
  issuerRef:
    name: prod-letsencrypt
    kind: ClusterIssuer
  commonName: netflux.io
  dnsNames:
    - netflux.io
    - git.netflux.io
    - grafana.netflux.io
    - netflux.io
    - caldav.netflux.io
    - solar-gateway.netflux.io
