apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 50m
    nginx.ingress.kubernetes.io/server-snippet: |
      location = /robots.txt {
        add_header Content-Type text/plain;
        return 200 "User-agent: Amazonbot\nDisallow: /\n\nUser-agent: BLEXBot\nDisallow: /\n\nUser-agent: SemrushBot\nDisallow: /\n\nUser-agent: AhrefsBot\nDisallow: /\n\nUser-agent: DotBot\nDisallow: /\n\nUser-agent: MJ12bot\nDisallow: /\n\nUser-agent: PetalBot\nDisallow: /\n\nUser-agent: ImagesiftBot\nDisallow: /\n\nUser-agent: BingBot\nCrawl-delay: 30\n";

      }

spec:
  rules:
  - host: k3s.netflux.io
    http:
      paths:
      - path: /test
        pathType: Prefix
        backend:
          service:
            name: whoami
            port:
              number: 5678
      - path: /
        pathType: Prefix
        backend:
          service:
            name: netflux-homepage
            port:
              name: http
  - host: grafana-k3s.netflux.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: grafana
            port:
              name: service
  tls:
    - hosts:
      - k3s.netflux.io
      - grafana-k3s.netflux.io
      secretName: prod-ingress-tls
