apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  annotations:
    # chain your middlewares, noting the @kubernetescrd suffix
    traefik.ingress.kubernetes.io/router.middlewares: |
      default-prod-redirect-ssl@kubernetescrd,default-prod-headers@kubernetescrd

spec:
  rules:
  - host: netflux.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: netflux-homepage
            port:
              name: http
  - host: grafana.netflux.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: grafana
            port:
              name: service
  - host: git.netflux.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: gitea
            port:
              name: http
  - host: caldav.netflux.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: radicale
            port:
              name: caldav
  - host: solar-gateway.netflux.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: solar-toolkit-gateway
            port:
              name: http
  - host: live.netflux.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: owncast
            port:
              name: http
  - host: tube.netflux.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: peertube
            port:
              name: http

  tls:
    - hosts:
      - netflux.io
      - grafana.netflux.io
      - git.netflux.io
      - caldav.netflux.io
      - solar-gateway.netflux.io
      - live.netflux.io
      - tube.netflux.io
      secretName: prod-ingress-tls
