---
namePrefix: prod-
resources:
- ../minimal-base

patches:
# Patch the ingress-nginx deployment to allow it to use a service with a
# namePrefix. See https://github.com/kubernetes/ingress-nginx/issues/2599#issuecomment-601170289.
- target:
    kind: Deployment
    name: ingress-nginx-controller
  path: deploy-ingress-nginx.yaml

# Patch the ingress-nginx-admission-create job to reference its webhook with a
# namePrefix.
- target:
    kind: Job
    name: ingress-nginx-admission-create
  path: job-ingress-nginx-admission-create.yaml

# Patch the ingress-nginx-admission-patch job to reference its webhook with a
# namePrefix.
- target:
    kind: Job
    name: ingress-nginx-admission-patch
  path: job-ingress-nginx-admission-patch.yaml
