---
namePrefix: prod-
resources:
- ../minimal-base
# cert-manager:
- inflated/cert-manager/templates/serviceaccount.yaml
- inflated/cert-manager/templates/cainjector-service.yaml
- inflated/cert-manager/templates/crds.yaml
- inflated/cert-manager/templates/webhook-rbac.yaml
- inflated/cert-manager/templates/deployment.yaml
- inflated/cert-manager/templates/cainjector-serviceaccount.yaml
- inflated/cert-manager/templates/webhook-serviceaccount.yaml
- inflated/cert-manager/templates/webhook-mutating-webhook.yaml
- inflated/cert-manager/templates/cainjector-deployment.yaml
- inflated/cert-manager/templates/startupapicheck-rbac.yaml
- inflated/cert-manager/templates/startupapicheck-serviceaccount.yaml
- inflated/cert-manager/templates/cainjector-rbac.yaml
- inflated/cert-manager/templates/service.yaml
- inflated/cert-manager/templates/webhook-service.yaml
- inflated/cert-manager/templates/webhook-validating-webhook.yaml
- inflated/cert-manager/templates/rbac.yaml
- inflated/cert-manager/templates/startupapicheck-job.yaml
- inflated/cert-manager/templates/webhook-deployment.yaml

patches:
# Patch the ingress-nginx deployment to allow it to use a service with a
# namePrefix. See https://github.com/kubernetes/ingress-nginx/issues/2599#issuecomment-601170289.
- target:
    kind: Deployment
    name: ingress-nginx-controller
  path: deploy-ingress-nginx.yaml

# Patch the ingress-nginx-admission-create job to reference its webhook with a
# namePrefix.
- target:
    kind: Job
    name: ingress-nginx-admission-create
  path: job-ingress-nginx-admission-create.yaml

# Patch the ingress-nginx-admission-patch job to reference its webhook with a
# namePrefix.
- target:
    kind: Job
    name: ingress-nginx-admission-patch
  path: job-ingress-nginx-admission-patch.yaml
