# Minimal version of base/kustomization.yml while migrating.
---
resources:
# metrics-server
- inflated/metrics-server/templates/serviceaccount.yaml
- inflated/metrics-server/templates/clusterrolebinding-auth-delegator.yaml
- inflated/metrics-server/templates/rolebinding.yaml
- inflated/metrics-server/templates/deployment.yaml
- inflated/metrics-server/templates/apiservice.yaml
- inflated/metrics-server/templates/clusterrole-aggregated-reader.yaml
- inflated/metrics-server/templates/service.yaml
- inflated/metrics-server/templates/clusterrole.yaml
- inflated/metrics-server/templates/clusterrolebinding.yaml
# ingress-nginx
- inflated/ingress-nginx/templates/controller-deployment.yaml
- inflated/ingress-nginx/templates/controller-serviceaccount.yaml
- inflated/ingress-nginx/templates/controller-rolebinding.yaml
- inflated/ingress-nginx/templates/controller-ingressclass.yaml
- inflated/ingress-nginx/templates/controller-service-metrics.yaml
- inflated/ingress-nginx/templates/clusterrole.yaml
- inflated/ingress-nginx/templates/controller-service.yaml
- inflated/ingress-nginx/templates/controller-service-webhook.yaml
- inflated/ingress-nginx/templates/controller-role.yaml
- inflated/ingress-nginx/templates/controller-configmap.yaml
- inflated/ingress-nginx/templates/admission-webhooks/job-patch/serviceaccount.yaml
- inflated/ingress-nginx/templates/admission-webhooks/job-patch/job-createSecret.yaml
- inflated/ingress-nginx/templates/admission-webhooks/job-patch/job-patchWebhook.yaml
- inflated/ingress-nginx/templates/admission-webhooks/job-patch/rolebinding.yaml
- inflated/ingress-nginx/templates/admission-webhooks/job-patch/role.yaml
- inflated/ingress-nginx/templates/admission-webhooks/job-patch/clusterrole.yaml
- inflated/ingress-nginx/templates/admission-webhooks/job-patch/clusterrolebinding.yaml
- inflated/ingress-nginx/templates/admission-webhooks/validating-webhook.yaml
- inflated/ingress-nginx/templates/clusterrolebinding.yaml
